default_stages: [commit, merge-commit, push, manual]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=1000"]

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          [
            wip,
            build,
            chore,
            ci,
            docs,
            feat,
            fix,
            perf,
            refactor,
            revert,
            style,
            test,
          ]
  - repo: local
    hooks:
      - id: eslint
        files: "^src/.*$"
        name: eslint
        entry: bash -c "npm i; npm run lint"
        language: node
